### ISSUE TITLE
Release 0.4.0

### ISSUE THREAD

**Issue by 12wrigja** [js-temporal/temporal-polyfill#139] opened 2022-02-18 21:07 UTC
I think now's a good time to create another release.

I'd like to target a cutoff point within the next week or so, and hopefully https://github.com/js-temporal/temporal-polyfill/pull/105 can land first? It would be great to have that included.

**Comment by 12wrigja** [comment] 2022-02-18 21:08
I can drive a release starting sometime late next week.

**Comment by justingrant** [comment] 2022-02-18 21:22
> hopefully #105 can land first? It would be great to have that included.

Agree. But I wouldn't hold the release for it. If it's ready, that's great. If not, we can pick it up in the next one.

**Comment by 12wrigja** [comment] 2022-03-04 03:24
I started working on this, but then hit a roadblock and forgot to post an update here.

I was trying to ensure that we had test262 coverage parity with the spec polyfill, and found that when I sync up the test262 repo to 2f592de0 that 62 tests are failing, all of which seem to be `year-zero.js` tests.

I think it's because we are missing [e60ef9eac7a35b67b065f25d6e560a9bf4ba8bd5](https://github.com/tc39/proposal-temporal/commit/e60ef9eac7a35b67b065f25d6e560a9bf4ba8bd5), and that made me wonder what else we might be missing.

**Comment by 12wrigja** [comment] 2022-03-04 05:40
My intent is to draft a release cut at 670cda6bd269db66c8ce97eb73f941b20abb92ec.

I skimmed over changes to tc39/proposal-temporal and I don't think anything else relevant is missing - most of the other commits seems to been test removals (as they've been ported to test262 - yay!).

**Comment by justingrant** [comment] 2022-03-04 06:04
Great!  Heads up I'm watching https://github.com/tc39/proposal-temporal/issues/2075, and if it's a bug then it may make sense to fix it before this release. Let's decide tomorrow.

**Comment by justingrant** [comment] 2022-03-04 06:05
False alarm. According to https://github.com/tc39/proposal-temporal/issues/2075#issuecomment-1058862771 it's not a bug. Release should be good to go!

**Comment by justingrant** [comment] 2022-03-07 20:09
Thanks so much @12wrigja for getting the release out the door! Closing.

**Closed by justingrant** 2022-03-07 20:09 UTC
