### ISSUE TITLE
First day of week in Japanese calendar is Sunday

### ISSUE THREAD

**Issue by akihironagai** [js-temporal/temporal-polyfill#220] opened 2023-02-07 08:53 UTC
First day of week in Japanese calendar is Sunday.

See: [https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/territory_information.html#JP](https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/territory_information.html#JP)

 Note: #208

```javascript
Temporal.PlainDate.from({ year: 2023, month: 1, day: 1, calendar: "iso8601" }).dayOfWeek // returns 7
Temporal.PlainDate.from({ year: 2023, month: 1, day: 1, calendar: "japanese" }).dayOfWeek // returns 7 but, it should 1
```

**Comment by 12wrigja** [comment] 2023-02-07 16:40
This seems very similar to https://github.com/js-temporal/temporal-polyfill/issues/208, which was closed as "working as intended" because `dayOfWeek` is not intended to be locale-dependent.

**Comment by ptomato** [comment] 2023-02-07 17:22
This might be different because #208 was about the Gregorian calendar, which has a locale-dependent first day of week; I don't know the situation with the Japanese calendar.

**Comment by justingrant** [comment] 2023-02-07 19:49
The current behavior is indeed "working as intended" for all calendars. I can provide a bit of context below. 

For any particular date, there are two questions you could ask relating to its day of the week:
1. **What's the name of this day of the week?** Although names vary across languages, almost all CLDR calendars share the same recurring 7-day week pattern. For this reason, it's helpful for days to have consistent indexes across calendars and languages, so that the identity of the day is known regardless of whether its name is  "Tuesday" in English or "火曜日" in Japanese.
2. **What order is this day in the week?** (e.g. first day of week, second day of week, etc.) This varies widely across countries.

Importantly, you can't answer both questions with a single numeric result; you need two different pieces of data. 

In Temporal, question (1) is answered by the `dayOfWeek` property. Regardless of the calendar or locale, you can use this index to look up a localized name in a map of names, and the same day will always use the same index, regardless of calendar or locale.

Question (2), is answered using a different, locale-dependent API: [`Intl.Locale.prototype.weekInfo`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/weekInfo). Note that the calendar can be included in the locale. Like this:

```js
new Intl.Locale("ja-JP-u-ca-japanese").weekInfo.firstDay;
// => 7 (which maps to 日曜日 in Japanese)
```

If the results of this Intl API aren't as expected, you can file an issue in the https://github.com/tc39/ecma402 repo. 

_@sffc @manishearth - please correct me if I got anything wrong above!_

**Comment by justingrant** [comment] 2023-04-02 05:10
I'm going to close this issue, as I believe that the current behavior is working as expected, because the non-Temporal API [Intl.Locale.prototype.weekInfo](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/weekInfo) is intended to solve the question of which weekday is the first of the week in a particular locale.

**Closed by justingrant** 2023-04-02 05:10 UTC
